package com.david.auction.exceptions;

public enum ErrorType {

    AUCTION_HOUSE_EXISTS,
    AUCTION_HOUSE_NOT_FOUND,
    AUCTION_NOT_FOUND,
    AUCTION_NOT_RUNNING,
    AUCTION_NOT_TERMINATED,
    AUCTION_NOT_ACCEPTED,
    AUCTION_NO_WINNER,
    AUCTION_EXISTS
}
